// ECommerce/seventysixcommerce-sveltekit/src/routes/policies/privacy/+page.svelte
<script lang="ts">
	import type { PageData } from "./$types";
	import { currentYear } from "$lib/utils/date";

	let { data }: { data: PageData } = $props();
</script>

<svelte:head>
	<title>Privacy Policy — SeventySixCommerce</title>
	<meta
		name="description"
		content="SeventySixCommerce privacy policy — how we handle your data."
	/>
	<link rel="canonical" href={`${data.baseUrl}/policies/privacy`} />
	<meta property="og:title" content="Privacy Policy — SeventySixCommerce" />
	<meta
		property="og:description"
		content="SeventySixCommerce privacy policy — how we handle your data."
	/>
	<meta property="og:type" content="website" />
	<meta property="og:url" content={`${data.baseUrl}/policies/privacy`} />
	<meta name="twitter:card" content="summary" />
</svelte:head>

<div class="mx-auto max-w-3xl px-6 py-16">
	<h1 class="text-3xl font-bold tracking-tight text-text-primary">
		Privacy Policy
	</h1>
	<div class="mt-8 space-y-6 text-text-secondary leading-relaxed">
		<p>Last updated: {currentYear()}</p>

		<h2 class="text-xl font-semibold text-text-primary">
			Information We Collect
		</h2>
		<p>
			We collect only the information necessary to process your order:
			name, shipping address, and email address. Payment information is
			handled securely by Stripe — we never see or store your card
			details.
		</p>

		<h2 class="text-xl font-semibold text-text-primary">
			How We Use Your Information
		</h2>
		<p>
			Your information is used solely to fulfill your order and send
			shipping notifications. We do not sell, rent, or share your personal
			information with third parties for marketing purposes.
		</p>

		<h2 class="text-xl font-semibold text-text-primary">Cookies</h2>
		<p>
			We use a single HTTP-only session cookie to maintain your shopping
			cart. No tracking cookies or third-party analytics are used.
		</p>

		<h2 class="text-xl font-semibold text-text-primary">Contact</h2>
		<p>
			For privacy-related inquiries, please contact us at
			privacy@SeventySixCommerce.art.
		</p>
	</div>
</div>

// ECommerce/seventysixcommerce-tanstack/src/routes/privacy.tsx
import { createFileRoute } from "@tanstack/react-router";
import type { JSX } from "react";
import { SITE_URL } from "~/lib/constants";

export const Route =
	createFileRoute("/privacy")(
		{
			head: () => ({
				meta: [
					{ title: "Privacy Policy \u2014 SeventySixCommerce" },
					{
						name: "description",
						content: "SeventySixCommerce privacy policy \u2014 how we handle your data."
					},
					{
						property: "og:title",
						content: "Privacy Policy \u2014 SeventySixCommerce"
					},
					{
						property: "og:description",
						content: "SeventySixCommerce privacy policy \u2014 how we handle your data."
					},
					{ property: "og:type", content: "website" },
					{ property: "og:url", content: `${SITE_URL}/privacy` },
					{ name: "twitter:card", content: "summary" }
				],
				links: [
					{ rel: "canonical", href: `${SITE_URL}/privacy` }
				]
			}),
			component: PrivacyPage
		});

/** Privacy policy page. */
function PrivacyPage(): JSX.Element
{
	return (
		<main className="mx-auto max-w-3xl px-4 py-16">
			<h1 className="mb-6 text-3xl font-bold">Privacy Policy</h1>
			<p className="mb-4 text-text-secondary">Last updated: 2026</p>

			<h2 className="mb-3 mt-8 text-xl font-semibold">
				Information We Collect
			</h2>
			<p className="mb-4 text-text-secondary">
				We collect your email address and shipping information when you place an order. Payment processing is
				handled entirely by Stripe — we never see or store your card details.
			</p>

			<h2 className="mb-3 mt-8 text-xl font-semibold">
				How We Use Your Data
			</h2>
			<p className="mb-4 text-text-secondary">
				Your data is used solely to fulfill your order and send shipping notifications. We do not sell, rent, or
				share your personal information with third parties except as required to complete your order (Printful
				for fulfillment, Brevo for email notifications).
			</p>

			<h2 className="mb-3 mt-8 text-xl font-semibold">Cookies</h2>
			<p className="mb-4 text-text-secondary">
				We use a session cookie for your shopping cart and a CSRF protection cookie. No tracking cookies are
				used.
			</p>

			<h2 className="mb-3 mt-8 text-xl font-semibold">Contact</h2>
			<p className="text-text-secondary">
				Questions about your data? Email us at privacy@SeventySixCommerce.store
			</p>
		</main>);
}
