// ECommerce/seventysixcommerce-tanstack/src/routes/terms.tsx
import { createFileRoute } from "@tanstack/react-router";
import type { JSX } from "react";
import { SITE_URL } from "~/lib/constants";

export const Route =
	createFileRoute("/terms")(
		{
			head: () => ({
				meta: [
					{ title: "Terms of Service \u2014 SeventySixCommerce" },
					{
						name: "description",
						content: "SeventySixCommerce terms of service."
					},
					{
						property: "og:title",
						content: "Terms of Service \u2014 SeventySixCommerce"
					},
					{
						property: "og:description",
						content: "SeventySixCommerce terms of service."
					},
					{ property: "og:type", content: "website" },
					{ property: "og:url", content: `${SITE_URL}/terms` },
					{ name: "twitter:card", content: "summary" }
				],
				links: [
					{ rel: "canonical", href: `${SITE_URL}/terms` }
				]
			}),
			component: TermsPage
		});

/** Terms of service page. */
function TermsPage(): JSX.Element
{
	return (
		<main className="mx-auto max-w-3xl px-4 py-16">
			<h1 className="mb-6 text-3xl font-bold">Terms of Service</h1>
			<p className="mb-4 text-text-secondary">Last updated: 2026</p>

			<h2 className="mb-3 mt-8 text-xl font-semibold">
				Orders & Payment
			</h2>
			<p className="mb-4 text-text-secondary">
				All payments are processed securely through Stripe. Prices are in USD and include applicable taxes where
				required. Orders are confirmed via email after successful payment.
			</p>

			<h2 className="mb-3 mt-8 text-xl font-semibold">Shipping</h2>
			<p className="mb-4 text-text-secondary">
				Products are printed on demand by our fulfillment partner (Printful) and typically ship within 3-7
				business days. Tracking information is provided via email once your order ships.
			</p>

			<h2 className="mb-3 mt-8 text-xl font-semibold">
				Returns & Refunds
			</h2>
			<p className="mb-4 text-text-secondary">
				Due to the custom, made-to-order nature of our products, we accept returns only for defective or damaged
				items. Please contact us within 14 days of delivery with photos of the issue.
			</p>

			<h2 className="mb-3 mt-8 text-xl font-semibold">
				Intellectual Property
			</h2>
			<p className="text-text-secondary">
				All artwork and designs are original works. Reproduction, redistribution, or commercial use of our
				artwork without written permission is prohibited.
			</p>
		</main>);
}

// ECommerce/seventysixcommerce-sveltekit/src/routes/policies/terms/+page.svelte
<script lang="ts">
	import type { PageData } from "./$types";
	import { currentYear } from "$lib/utils/date";

	let { data }: { data: PageData } = $props();
</script>

<svelte:head>
	<title>Terms of Service — SeventySixCommerce</title>
	<meta name="description" content="SeventySixCommerce terms of service." />
	<link rel="canonical" href={`${data.baseUrl}/policies/terms`} />
	<meta property="og:title" content="Terms of Service — SeventySixCommerce" />
	<meta
		property="og:description"
		content="SeventySixCommerce terms of service."
	/>
	<meta property="og:type" content="website" />
	<meta property="og:url" content={`${data.baseUrl}/policies/terms`} />
	<meta name="twitter:card" content="summary" />
</svelte:head>

<div class="mx-auto max-w-3xl px-6 py-16">
	<h1 class="text-3xl font-bold tracking-tight text-text-primary">
		Terms of Service
	</h1>
	<div class="mt-8 space-y-6 text-text-secondary leading-relaxed">
		<p>Last updated: {currentYear()}</p>

		<h2 class="text-xl font-semibold text-text-primary">Agreement</h2>
		<p>
			By using SeventySixCommerce, you agree to these terms. If you do not
			agree, please do not use our services.
		</p>

		<h2 class="text-xl font-semibold text-text-primary">Products</h2>
		<p>
			All products are made to order through our print-on-demand service.
			Colors may vary slightly from screen display. We strive for accuracy
			in all product descriptions and images.
		</p>

		<h2 class="text-xl font-semibold text-text-primary">Pricing</h2>
		<p>
			All prices are listed in USD. We reserve the right to modify prices
			at any time. Orders are charged at the price displayed at the time
			of purchase.
		</p>

		<h2 class="text-xl font-semibold text-text-primary">
			Intellectual Property
		</h2>
		<p>
			All artwork and designs are the property of SeventySixCommerce and
			its artists. Reproduction without written permission is prohibited.
		</p>
	</div>
</div>
