// ECommerce/seventysixcommerce-tanstack/src/routes/shop/index.tsx
import { isPresent } from "@seventysixcommerce/shared/utils";
import { createFileRoute, Link } from "@tanstack/react-router";
import type { JSX } from "react";
import { SITE_URL } from "~/lib/constants";
import { getCategories } from "~/server/functions/products";
import type { Category } from "~/server/functions/products";
import { queueLog } from "~/server/log-forwarder";
import { recordPageView } from "~/server/metrics";

export const Route =
	createFileRoute("/shop/")(
		{
			loader: async () =>
			{
				recordPageView("shop");
				queueLog(
					{
						logLevel: "Information",
						message: "Page view: shop"
					});

				const categories: Category[] =
					await getCategories();
				return { categories };
			},
			head: () => ({
				meta: [
					{ title: "Shop — SeventySixCommerce Art Merchandise" },
					{
						name: "description",
						content: "Browse original art merchandise — posters, apparel, mugs and more."
					},
					{
						property: "og:title",
						content: "Shop — SeventySixCommerce Art Merchandise"
					},
					{
						property: "og:description",
						content: "Browse original art merchandise — posters, apparel, mugs and more."
					},
					{ property: "og:type", content: "website" },
					{ property: "og:url", content: `${SITE_URL}/shop` },
					{ name: "twitter:card", content: "summary" },
					{
						name: "twitter:title",
						content: "Shop — SeventySixCommerce Art Merchandise"
					},
					{
						name: "twitter:description",
						content: "Browse original art merchandise — posters, apparel, mugs and more."
					}
				],
				links: [{ rel: "canonical", href: `${SITE_URL}/shop` }]
			}),
			component: ShopPage
		});

function ShopPage(): JSX.Element
{
	const { categories } =
		Route.useLoaderData();

	return (
		<div className="mx-auto max-w-7xl px-4 py-8 sm:px-6 lg:px-8">
			<h1 className="mb-8 text-3xl font-bold text-text-primary">Shop</h1>
			<div className="grid grid-cols-1 gap-6 sm:grid-cols-2 lg:grid-cols-3">
				{categories.map((category: Category) => (
					<Link
						key={category.id}
						to="/shop/$category"
						params={{ category: category.slug }}
						className="group block rounded-lg border border-border p-6 transition-shadow hover:shadow-md"
					>
						<h2 className="mb-2 text-xl font-semibold text-text-primary group-hover:text-text-secondary">
							{category.name}
						</h2>
						{isPresent(category.description) && (
							<p className="mb-4 text-sm text-text-muted">
								{category.description}
							</p>)}
						<span className="text-sm font-medium text-text-primary underline group-hover:no-underline">
							Browse {category.productCount} {category.productCount === 1 ? "product" : "products"} →
						</span>
					</Link>))}
			</div>
		</div>);
}

// seventysixcommerce-sveltekit/src/routes/shop/+page.svelte
<script lang="ts">
	import type { PageData } from "./$types";

	let { data }: { data: PageData } = $props();
</script>

<svelte:head>
	<title>Shop — SeventySixCommerce</title>
	<meta
		name="description"
		content="Browse all SeventySixCommerce art merchandise categories."
	/>
	<link rel="canonical" href={`${data.baseUrl}/shop`} />
	<meta property="og:title" content="Shop — SeventySixCommerce" />
	<meta
		property="og:description"
		content="Browse all SeventySixCommerce art merchandise categories."
	/>
	<meta property="og:type" content="website" />
	<meta property="og:url" content={`${data.baseUrl}/shop`} />
	<meta name="twitter:card" content="summary" />
	<meta name="twitter:title" content="Shop — SeventySixCommerce" />
	<meta
		name="twitter:description"
		content="Browse all SeventySixCommerce art merchandise categories."
	/>
</svelte:head>

<div class="mx-auto max-w-7xl px-6 py-16">
	<h1 class="text-3xl font-bold tracking-tight text-text-primary">Shop</h1>

	<div class="mt-8 grid grid-cols-1 gap-6 sm:grid-cols-2 lg:grid-cols-3">
		{#each data.categories as category}
			<a
				href="/shop/{category.slug}"
				class="group rounded-lg border border-border p-6 transition-colors hover:border-accent hover:bg-accent/10"
			>
				<h2
					class="text-lg font-semibold text-text-primary group-hover:text-accent"
				>
					{category.name}
				</h2>
				{#if category.description}
					<p class="mt-2 text-sm text-text-secondary">
						{category.description}
					</p>
				{/if}
				<p class="mt-2 text-sm text-text-muted">
					{category.productCount} products
				</p>
			</a>
		{/each}
	</div>
</div>
