// ECommerce/seventysixcommerce-sveltekit/src/lib/components/seo/JsonLd.svelte
<!--
  @component
  Renders JSON-LD structured data in a script tag for SEO.
  Escapes closing script tags to prevent XSS injection.
-->
<script lang="ts">
	let { schema }: { schema: Record<string, unknown> } = $props();

	/** Safely serializes JSON-LD, escaping sequences that could break out of script tags. */
	function safeJsonLd(data: Record<string, unknown>): string {
		return JSON.stringify(data).replace(/</g, "\\u003c");
	}
</script>

<svelte:head>
	{@html '<script type="application/ld+json">' + safeJsonLd(schema) + '</script>'}
</svelte:head>

// ECommerce/seventysixcommerce-tanstack/src/components/seo/JsonLd.tsx
import type { JSX } from "react";

/**
 * Safely serializes JSON-LD, escaping sequences that could break out of script tags.
 * @param data - The structured data object to serialize.
 * @returns Escaped JSON string safe for embedding in script tags.
 */
function safeJsonLd(data: object): string
{
	return JSON
		.stringify(data)
		.replace(/</g, "\\u003c");
}

/**
 * Renders a JSON-LD structured data script tag.
 * @param data - The structured data object conforming to Schema.org vocabulary.
 * @returns A script element with serialized JSON-LD content.
 */
export function JsonLd({ data }: Readonly<{ data: object; }>): JSX.Element
{
	return (
		<script
			type="application/ld+json"
			dangerouslySetInnerHTML={{ __html: safeJsonLd(data) }}
		/>);
}
